package br.com.cidadeemfoco.enums;

public enum OccurrenceType {
    ALAGAMENTO,
    ENCHENTE,
    QUEDA_ARVORE,
    DESLIZAMENTO,
    VENTOS_FORTES,
    RESSACA_MARITIMA,
    INCENDIO,
    CHUVA_INTENSA,
    BURACO_RUA,
    BUEIRO_ENTUPIDO,
    POSTE_DANIFICADO,
    SEMAFORO_COM_PROBLEMA,
    RUA_BLOQUEADA,
    FALTA_ILUMINACAO,
    ARVORE_OBSTRUINDO_VIA,
    OUTRO
}

